version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=grafana_db
    ports:
      - "3306:3306"
    volumes:
      # - ../mysql:/var/lib/mysql
      - ../mysql/data.sql:/docker-entrypoint-initdb.d/data.sql


  grafana:
    image: grafana/grafana:8.5.22
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    network_mode: host
    volumes:
      - ../grafana/storage:/var/lib/grafana
      - ../grafana/custom.ini:/etc/grafana/grafana.ini
      - ../openvidu-video-panel:/var/lib/grafana/plugins
