version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    network_mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=grafana_db
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/openvidu_dashboard.json
    ports:
      - "3306:3306"
    # volumes:
      # - ../mysql:/var/lib/mysql


  grafana:
    image: grafana/grafana:8.5.22
    container_name: grafana
    restart: always
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    network_mode: host
    environment:
      - MYSQL_URL=localhost:3306
      - MYSQL_DATABASE=grafana_db
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
    volumes:
      - ../grafana/storage:/var/lib/grafana
      - ../grafana/custom.ini:/etc/grafana/grafana.ini
      - ../openvidu-video-panel:/var/lib/grafana/plugins
      - ../grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ../grafana/dashboards:/var/lib/grafana/dashboards
      - ../grafana/datasources:/var/lib/grafana/datasources


  db_initializer:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    depends_on:
      - mysql
    container_name: db_initializer
    restart: on-failure
    network_mode: host
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_HOST=localhost
      - DB_NAME=grafana_db
      - VIDEOS_URL=https://s3.eu-west-1.amazonaws.com/public.openvidu.io/bbb_640x480.mkv,https://s3.eu-west-1.amazonaws.com/public.openvidu.io/fakevideo_h264_opus.mkv

